package ia.animais.impl;

import ia.animais.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultIrracional <br>
 * @version generated on Thu May 07 17:00:01 BRT 2015 by caio
 */
public class DefaultIrracional extends WrappedIndividualImpl implements Irracional {

    public DefaultIrracional(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
