package ia.animais;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Thu May 07 17:00:00 BRT 2015 by caio
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#agressivo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AGRESSIVO.<p>
     * 
     */
    public static final OWLClass CLASS_AGRESSIVO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#agressivo"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#anfibios
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANFIBIOS.<p>
     * 
     */
    public static final OWLClass CLASS_ANFIBIOS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#anfibios"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#animal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANIMAL.<p>
     * 
     */
    public static final OWLClass CLASS_ANIMAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#animal"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#aquatico
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AQUATICO.<p>
     * 
     */
    public static final OWLClass CLASS_AQUATICO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#aquatico"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#assexuada
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ASSEXUADA.<p>
     * 
     */
    public static final OWLClass CLASS_ASSEXUADA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#assexuada"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#aves
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AVES.<p>
     * 
     */
    public static final OWLClass CLASS_AVES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#aves"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#braqucaio.caioAl
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BRAQUcaio.caioAL.<p>
     * 
     */
    public static final OWLClass CLASS_BRAQUcaio.caioAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#braqucaio.caioAl"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#calmo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CALMO.<p>
     * 
     */
    public static final OWLClass CLASS_CALMO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#calmo"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#caminha
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CAMINHA.<p>
     * 
     */
    public static final OWLClass CLASS_CAMINHA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#caminha"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#caracteristicas
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CARACTERISTICAS.<p>
     * 
     */
    public static final OWLClass CLASS_CARACTERISTICAS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#caracteristicas"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#classe
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLASSE.<p>
     * 
     */
    public static final OWLClass CLASS_CLASSE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#classe"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#cobertura
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COBERTURA.<p>
     * 
     */
    public static final OWLClass CLASS_COBERTURA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#cobertura"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#comportamento
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPORTAMENTO.<p>
     * 
     */
    public static final OWLClass CLASS_COMPORTAMENTO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#comportamento"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#concha
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONCHA.<p>
     * 
     */
    public static final OWLClass CLASS_CONCHA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#concha"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#cutanea
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CUTANEA.<p>
     * 
     */
    public static final OWLClass CLASS_CUTANEA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#cutanea"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#escamas
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ESCAMAS.<p>
     * 
     */
    public static final OWLClass CLASS_ESCAMAS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#escamas"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#habitat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HABITAT.<p>
     * 
     */
    public static final OWLClass CLASS_HABITAT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#habitat"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#irracional
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IRRACIONAL.<p>
     * 
     */
    public static final OWLClass CLASS_IRRACIONAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#irracional"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#locomoçao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOCOMOÇAO.<p>
     * 
     */
    public static final OWLClass CLASS_LOCOMOÇAO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#locomoçao"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#mamiferos
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MAMIFEROS.<p>
     * 
     */
    public static final OWLClass CLASS_MAMIFEROS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#mamiferos"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#nada
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NADA.<p>
     * 
     */
    public static final OWLClass CLASS_NADA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#nada"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#peixes
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PEIXES.<p>
     * 
     */
    public static final OWLClass CLASS_PEIXES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#peixes"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#pelos
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PELOS.<p>
     * 
     */
    public static final OWLClass CLASS_PELOS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#pelos"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#penas
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PENAS.<p>
     * 
     */
    public static final OWLClass CLASS_PENAS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#penas"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#pulmonar
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PULMONAR.<p>
     * 
     */
    public static final OWLClass CLASS_PULMONAR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#pulmonar"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#raciocinio
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RACIOCINIO.<p>
     * 
     */
    public static final OWLClass CLASS_RACIOCINIO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#raciocinio"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#racional
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RACIONAL.<p>
     * 
     */
    public static final OWLClass CLASS_RACIONAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#racional"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#rasteja
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RASTEJA.<p>
     * 
     */
    public static final OWLClass CLASS_RASTEJA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#rasteja"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#reproducao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REPRODUCAO.<p>
     * 
     */
    public static final OWLClass CLASS_REPRODUCAO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#reproducao"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#repteis
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REPTEIS.<p>
     * 
     */
    public static final OWLClass CLASS_REPTEIS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#repteis"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#respiraçao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESPIRAÇAO.<p>
     * 
     */
    public static final OWLClass CLASS_RESPIRAÇAO = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#respiraçao"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#salta
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SALTA.<p>
     * 
     */
    public static final OWLClass CLASS_SALTA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#salta"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#sexuada
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEXUADA.<p>
     * 
     */
    public static final OWLClass CLASS_SEXUADA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#sexuada"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#terrestre
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TERRESTRE.<p>
     * 
     */
    public static final OWLClass CLASS_TERRESTRE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#terrestre"));

    /* ***************************************************
     * Class http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#voa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VOA.<p>
     * 
     */
    public static final OWLClass CLASS_VOA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#voa"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#cobertoPor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COBERTOPOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COBERTOPOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#cobertoPor"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#comportamento
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMPORTAMENTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMPORTAMENTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#comportamento"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#ehIrracional
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EHIRRACIONAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EHIRRACIONAL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#ehIrracional"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#ehRacional
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EHRACIONAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EHRACIONAL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#ehRacional"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#habitaMeio
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HABITAMEIO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HABITAMEIO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#habitaMeio"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#maiorQue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MAIORQUE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MAIORQUE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#maiorQue"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#menorQue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MENORQUE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MENORQUE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#menorQue"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#respiração
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RESPIRAÇÃO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RESPIRAÇÃO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#respiração"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#seLocomove
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SELOCOMOVE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SELOCOMOVE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#seLocomove"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#seReproduz
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SEREPRODUZ.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SEREPRODUZ = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#seReproduz"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));


}
