package ia.animais.impl;

import ia.animais.Braquial;

import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;

/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultBraqucaio.caioAl <br>
 *
 * @version generated on Thu May 07 17:00:01 BRT 2015 by caio
 */
public class DefaultBraquial extends WrappedIndividualImpl implements Braquial {

	public DefaultBraquial(CodeGenerationInference inference, IRI iri) {
		super(inference, iri);
	}

}
