package ia.animais.impl;

import ia.animais.Anfibios;
import ia.animais.Animal;
import ia.animais.Cobertura;
import ia.animais.Comportamento;
import ia.animais.Habitat;
import ia.animais.Locomoçao;
import ia.animais.Raciocinio;
import ia.animais.Reproducao;
import ia.animais.Vocabulary;

import java.util.Collection;

import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;

/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAnfibios <br>
 * 
 * @version generated on Thu May 07 17:00:00 BRT 2015 by caio
 */
public class DefaultAnfibios extends WrappedIndividualImpl implements Anfibios {

	public DefaultAnfibios(CodeGenerationInference inference, IRI iri) {
		super(inference, iri);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#cobertoPor
	 */

	public Collection<? extends Cobertura> getCobertoPor() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_COBERTOPOR, DefaultCobertura.class);
	}

	public boolean hasCobertoPor() {
		return !this.getCobertoPor().isEmpty();
	}

	public void addCobertoPor(Cobertura newCobertoPor) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_COBERTOPOR, newCobertoPor);
	}

	public void removeCobertoPor(Cobertura oldCobertoPor) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_COBERTOPOR, oldCobertoPor);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#comportamento
	 */

	public Collection<? extends Comportamento> getComportamento() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_COMPORTAMENTO, DefaultComportamento.class);
	}

	public boolean hasComportamento() {
		return !this.getComportamento().isEmpty();
	}

	public void addComportamento(Comportamento newComportamento) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_COMPORTAMENTO, newComportamento);
	}

	public void removeComportamento(Comportamento oldComportamento) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_COMPORTAMENTO, oldComportamento);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#ehIrracional
	 */

	public Collection<? extends Raciocinio> getEhIrracional() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_EHIRRACIONAL, DefaultRaciocinio.class);
	}

	public boolean hasEhIrracional() {
		return !this.getEhIrracional().isEmpty();
	}

	public void addEhIrracional(Raciocinio newEhIrracional) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_EHIRRACIONAL, newEhIrracional);
	}

	public void removeEhIrracional(Raciocinio oldEhIrracional) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_EHIRRACIONAL, oldEhIrracional);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#ehRacional
	 */

	public Collection<? extends Raciocinio> getEhRacional() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_EHRACIONAL, DefaultRaciocinio.class);
	}

	public boolean hasEhRacional() {
		return !this.getEhRacional().isEmpty();
	}

	public void addEhRacional(Raciocinio newEhRacional) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_EHRACIONAL, newEhRacional);
	}

	public void removeEhRacional(Raciocinio oldEhRacional) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_EHRACIONAL, oldEhRacional);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#habitaMeio
	 */

	public Collection<? extends Habitat> getHabitaMeio() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_HABITAMEIO, DefaultHabitat.class);
	}

	public boolean hasHabitaMeio() {
		return !this.getHabitaMeio().isEmpty();
	}

	public void addHabitaMeio(Habitat newHabitaMeio) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_HABITAMEIO, newHabitaMeio);
	}

	public void removeHabitaMeio(Habitat oldHabitaMeio) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_HABITAMEIO, oldHabitaMeio);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#maiorQue
	 */

	public Collection<? extends Animal> getMaiorQue() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_MAIORQUE, DefaultAnimal.class);
	}

	public boolean hasMaiorQue() {
		return !this.getMaiorQue().isEmpty();
	}

	public void addMaiorQue(Animal newMaiorQue) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_MAIORQUE, newMaiorQue);
	}

	public void removeMaiorQue(Animal oldMaiorQue) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_MAIORQUE, oldMaiorQue);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#menorQue
	 */

	public Collection<? extends Animal> getMenorQue() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_MENORQUE, DefaultAnimal.class);
	}

	public boolean hasMenorQue() {
		return !this.getMenorQue().isEmpty();
	}

	public void addMenorQue(Animal newMenorQue) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_MENORQUE, newMenorQue);
	}

	public void removeMenorQue(Animal oldMenorQue) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_MENORQUE, oldMenorQue);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#respiração
	 */

	public Collection<? extends Reproducao> getRespiração() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_RESPIRAÇÃO, DefaultReproducao.class);
	}

	public boolean hasRespiração() {
		return !this.getRespiração().isEmpty();
	}

	public void addRespiração(Reproducao newRespiração) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_RESPIRAÇÃO, newRespiração);
	}

	public void removeRespiração(Reproducao oldRespiração) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_RESPIRAÇÃO, oldRespiração);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#seLocomove
	 */

	public Collection<? extends Locomoçao> getSeLocomove() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_SELOCOMOVE, DefaultLocomoçao.class);
	}

	public boolean hasSeLocomove() {
		return !this.getSeLocomove().isEmpty();
	}

	public void addSeLocomove(Locomoçao newSeLocomove) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_SELOCOMOVE, newSeLocomove);
	}

	public void removeSeLocomove(Locomoçao oldSeLocomove) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_SELOCOMOVE, oldSeLocomove);
	}

	/* ***************************************************
	 * Object Property
	 * http://www.semanticweb.org/caio/ontologies/2015/3/untitled
	 * -ontology-3#seReproduz
	 */

	public Collection<? extends Reproducao> getSeReproduz() {
		return this.getDelegate().getPropertyValues(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_SEREPRODUZ, DefaultReproducao.class);
	}

	public boolean hasSeReproduz() {
		return !this.getSeReproduz().isEmpty();
	}

	public void addSeReproduz(Reproducao newSeReproduz) {
		this.getDelegate().addPropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_SEREPRODUZ, newSeReproduz);
	}

	public void removeSeReproduz(Reproducao oldSeReproduz) {
		this.getDelegate().removePropertyValue(this.getOwlIndividual(), Vocabulary.OBJECT_PROPERTY_SEREPRODUZ, oldSeReproduz);
	}

}
