package ia.animais.impl;

import ia.animais.Respiracao;

import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;
import org.protege.owl.codegeneration.inference.CodeGenerationInference;
import org.semanticweb.owlapi.model.IRI;

/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultRespiraçao <br>
 * 
 * @version generated on Thu May 07 17:00:01 BRT 2015 by caio
 */
public class DefaultRespiracao extends WrappedIndividualImpl implements Respiracao {

	public DefaultRespiracao(CodeGenerationInference inference, IRI iri) {
		super(inference, iri);
	}

}
