package ia.animais;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 *
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Braqucaio.caioAl <br>
 *
 * @version generated on Thu May 07 17:00:01 BRT 2015 by caio
 */

public interface Braquial extends Respiracao {

	/* ***************************************************
	 * Common interfaces
	 */

	OWLNamedIndividual getOwlIndividual();

	OWLOntology getOwlOntology();

	void delete();

}
