package ia.animais;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Mamiferos <br>
 * @version generated on Thu May 07 17:00:01 BRT 2015 by caio
 */

public interface Mamiferos extends Classe {

    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#cobertoPor
     */
     
    /**
     * Gets all property values for the cobertoPor property.<p>
     * 
     * @returns a collection of values for the cobertoPor property.
     */
    Collection<? extends Cobertura> getCobertoPor();

    /**
     * Checks if the class has a cobertoPor property value.<p>
     * 
     * @return true if there is a cobertoPor property value.
     */
    boolean hasCobertoPor();

    /**
     * Adds a cobertoPor property value.<p>
     * 
     * @param newCobertoPor the cobertoPor property value to be added
     */
    void addCobertoPor(Cobertura newCobertoPor);

    /**
     * Removes a cobertoPor property value.<p>
     * 
     * @param oldCobertoPor the cobertoPor property value to be removed.
     */
    void removeCobertoPor(Cobertura oldCobertoPor);


    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#comportamento
     */
     
    /**
     * Gets all property values for the comportamento property.<p>
     * 
     * @returns a collection of values for the comportamento property.
     */
    Collection<? extends Comportamento> getComportamento();

    /**
     * Checks if the class has a comportamento property value.<p>
     * 
     * @return true if there is a comportamento property value.
     */
    boolean hasComportamento();

    /**
     * Adds a comportamento property value.<p>
     * 
     * @param newComportamento the comportamento property value to be added
     */
    void addComportamento(Comportamento newComportamento);

    /**
     * Removes a comportamento property value.<p>
     * 
     * @param oldComportamento the comportamento property value to be removed.
     */
    void removeComportamento(Comportamento oldComportamento);


    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#ehIrracional
     */
     
    /**
     * Gets all property values for the ehIrracional property.<p>
     * 
     * @returns a collection of values for the ehIrracional property.
     */
    Collection<? extends Raciocinio> getEhIrracional();

    /**
     * Checks if the class has a ehIrracional property value.<p>
     * 
     * @return true if there is a ehIrracional property value.
     */
    boolean hasEhIrracional();

    /**
     * Adds a ehIrracional property value.<p>
     * 
     * @param newEhIrracional the ehIrracional property value to be added
     */
    void addEhIrracional(Raciocinio newEhIrracional);

    /**
     * Removes a ehIrracional property value.<p>
     * 
     * @param oldEhIrracional the ehIrracional property value to be removed.
     */
    void removeEhIrracional(Raciocinio oldEhIrracional);


    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#ehRacional
     */
     
    /**
     * Gets all property values for the ehRacional property.<p>
     * 
     * @returns a collection of values for the ehRacional property.
     */
    Collection<? extends Raciocinio> getEhRacional();

    /**
     * Checks if the class has a ehRacional property value.<p>
     * 
     * @return true if there is a ehRacional property value.
     */
    boolean hasEhRacional();

    /**
     * Adds a ehRacional property value.<p>
     * 
     * @param newEhRacional the ehRacional property value to be added
     */
    void addEhRacional(Raciocinio newEhRacional);

    /**
     * Removes a ehRacional property value.<p>
     * 
     * @param oldEhRacional the ehRacional property value to be removed.
     */
    void removeEhRacional(Raciocinio oldEhRacional);


    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#habitaMeio
     */
     
    /**
     * Gets all property values for the habitaMeio property.<p>
     * 
     * @returns a collection of values for the habitaMeio property.
     */
    Collection<? extends Habitat> getHabitaMeio();

    /**
     * Checks if the class has a habitaMeio property value.<p>
     * 
     * @return true if there is a habitaMeio property value.
     */
    boolean hasHabitaMeio();

    /**
     * Adds a habitaMeio property value.<p>
     * 
     * @param newHabitaMeio the habitaMeio property value to be added
     */
    void addHabitaMeio(Habitat newHabitaMeio);

    /**
     * Removes a habitaMeio property value.<p>
     * 
     * @param oldHabitaMeio the habitaMeio property value to be removed.
     */
    void removeHabitaMeio(Habitat oldHabitaMeio);


    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#maiorQue
     */
     
    /**
     * Gets all property values for the maiorQue property.<p>
     * 
     * @returns a collection of values for the maiorQue property.
     */
    Collection<? extends Animal> getMaiorQue();

    /**
     * Checks if the class has a maiorQue property value.<p>
     * 
     * @return true if there is a maiorQue property value.
     */
    boolean hasMaiorQue();

    /**
     * Adds a maiorQue property value.<p>
     * 
     * @param newMaiorQue the maiorQue property value to be added
     */
    void addMaiorQue(Animal newMaiorQue);

    /**
     * Removes a maiorQue property value.<p>
     * 
     * @param oldMaiorQue the maiorQue property value to be removed.
     */
    void removeMaiorQue(Animal oldMaiorQue);


    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#menorQue
     */
     
    /**
     * Gets all property values for the menorQue property.<p>
     * 
     * @returns a collection of values for the menorQue property.
     */
    Collection<? extends Animal> getMenorQue();

    /**
     * Checks if the class has a menorQue property value.<p>
     * 
     * @return true if there is a menorQue property value.
     */
    boolean hasMenorQue();

    /**
     * Adds a menorQue property value.<p>
     * 
     * @param newMenorQue the menorQue property value to be added
     */
    void addMenorQue(Animal newMenorQue);

    /**
     * Removes a menorQue property value.<p>
     * 
     * @param oldMenorQue the menorQue property value to be removed.
     */
    void removeMenorQue(Animal oldMenorQue);


    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#respiração
     */
     
    /**
     * Gets all property values for the respiração property.<p>
     * 
     * @returns a collection of values for the respiração property.
     */
    Collection<? extends Reproducao> getRespiração();

    /**
     * Checks if the class has a respiração property value.<p>
     * 
     * @return true if there is a respiração property value.
     */
    boolean hasRespiração();

    /**
     * Adds a respiração property value.<p>
     * 
     * @param newRespiração the respiração property value to be added
     */
    void addRespiração(Reproducao newRespiração);

    /**
     * Removes a respiração property value.<p>
     * 
     * @param oldRespiração the respiração property value to be removed.
     */
    void removeRespiração(Reproducao oldRespiração);


    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#seLocomove
     */
     
    /**
     * Gets all property values for the seLocomove property.<p>
     * 
     * @returns a collection of values for the seLocomove property.
     */
    Collection<? extends Locomoçao> getSeLocomove();

    /**
     * Checks if the class has a seLocomove property value.<p>
     * 
     * @return true if there is a seLocomove property value.
     */
    boolean hasSeLocomove();

    /**
     * Adds a seLocomove property value.<p>
     * 
     * @param newSeLocomove the seLocomove property value to be added
     */
    void addSeLocomove(Locomoçao newSeLocomove);

    /**
     * Removes a seLocomove property value.<p>
     * 
     * @param oldSeLocomove the seLocomove property value to be removed.
     */
    void removeSeLocomove(Locomoçao oldSeLocomove);


    /* ***************************************************
     * Property http://www.semanticweb.org/caio/ontologies/2015/3/untitled-ontology-3#seReproduz
     */
     
    /**
     * Gets all property values for the seReproduz property.<p>
     * 
     * @returns a collection of values for the seReproduz property.
     */
    Collection<? extends Reproducao> getSeReproduz();

    /**
     * Checks if the class has a seReproduz property value.<p>
     * 
     * @return true if there is a seReproduz property value.
     */
    boolean hasSeReproduz();

    /**
     * Adds a seReproduz property value.<p>
     * 
     * @param newSeReproduz the seReproduz property value to be added
     */
    void addSeReproduz(Reproducao newSeReproduz);

    /**
     * Removes a seReproduz property value.<p>
     * 
     * @param oldSeReproduz the seReproduz property value to be removed.
     */
    void removeSeReproduz(Reproducao oldSeReproduz);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
